//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence_Niveau_Interne
    {
        public int id_Competence { get; set; }
        public int id_Utilisateur { get; set; }
        public Nullable<int> id_Niveau { get; set; }
        public Nullable<bool> IsTuteur { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual Niveau Niveau { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
