//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int id_Likeur { get; set; }
        public int id_EmployeQuiSeFaitLike { get; set; }
        public int note { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Employe Employe1 { get; set; }
    }
}
