//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string Description { get; set; }
        public int id_Room { get; set; }
        public int id_Envoyeur { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Room Room { get; set; }
    }
}
