//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Traduction
    {
        public int idLangue { get; set; }
        public int idService { get; set; }
        public string NomTraduit { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Service Service { get; set; }
    }
}
