//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraductionPay
    {
        public int idPays { get; set; }
        public int idLangue { get; set; }
        public string nom { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Pay Pay { get; set; }
    }
}
