//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMarcassin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Competence_Niveau_Interne = new HashSet<Competence_Niveau_Interne>();
        }
    
        public int id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string NumeroDeTelephone { get; set; }
        public string Adresse_Mail { get; set; }
        public string Adresse { get; set; }
        public int id_Ville { get; set; }
        public int id_Entreprise { get; set; }
        public bool Sexe { get; set; }
        public Nullable<System.DateTime> DateDeNaissance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competence_Niveau_Interne> Competence_Niveau_Interne { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Entreprise Entreprise { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
